### ISSUE TITLE
Extension doesn't work for some reason on Mac

### ISSUE THREAD

**Issue by Glasov** [samuser107/zed-java-extension#3]
Im using Zed 0.123.6 on my mac, ventura v. 13.6:
<img width="479" alt="image" src="https://github.com/samuser107/zed-java-extension/assets/30201463/efca3f2e-b339-473b-9b80-10a69212c518">

I've installed the java extension, but for some reason it just won't work. Other languages do, and language server is on

<img width="987" alt="image" src="https://github.com/samuser107/zed-java-extension/assets/30201463/ee39a229-d346-476b-970f-4f1c7cbbdd09">

Any thoughts what could be wrong?

**Comment by samuser107** [comment]
Have you selected java in the language section on the bottom right corner?

**Comment by Glasov** [comment]
> Have you selected java in the language section on the bottom right corner?

I didn't. Thanks, now it does work!
